var a = 5;
console.log(a);
//this is a simple my name program
var myName = "BushraQanam";
console.log(myName);
myName = "alina sahrish";
console.log(myName);
myName = "aairah inshrah";
console.log(myName);
myName = "aizah zainab";
console.log(myName);
myName = "amaan ahmed";
console.log(myName);
myName = "numa noorin";
console.log(myName);
//this is a simple my age program
var my_age = 40;
console.log(my_age);
my_age = 14;
console.log(my_age);
my_age = 8;
console.log(my_age);
my_age = 7;
console.log(my_age);
my_age = 18;
console.log(my_age);
my_age = 20;
console.log(my_age);
//this is a simple my cars program
var MyCars = true;
console.log(MyCars);
MyCars = false;
console.log(MyCars);
MyCars = true;
console.log(MyCars);
MyCars = false;
console.log(MyCars);
MyCars = true;
console.log(MyCars);
var myArea = "hello world";
console.log(myArea);
var number = 10;
console.log(number);
number = 20;
console.log(number);
var myBooks = "bookcaes";
console.log(myBooks);
